version: '3'
services:
  app:
    environment:
      - DB_HOST=localhost
      - DB_PORT=31025
      - DB_NAME=environbit
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_TABLE=dados_base
      - RABBITMQ_USER=admin
      - RABBITMQ_PWD=admin
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=queue_test
      - MINIO_URL=192.168.30.21:30688
      - MINIO_SECURE=False
      - MINIO_SECRET_KEY=JACHvXYjV5tgQBiAWb9zizVrEY75PWGOgwzLtxk7
      - MINIO_ACCESS_KEY=f92RzGA47dUK5Ck4YwCqe
      - MINIO_BUCKET_NAME=environbit
      - DATA_LAKE=minio
      - TAXONOMY_FILE=app/static/taxonomy_file.csv
      - TRANSFORMATION_DIR=/tmp/transformation/
    build:
      context: ../..
      dockerfile: composes/app/Dockerfile